#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: petclinic-ingress
#  namespace: petclinic
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: www.team3.com
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: petclinic
#                port:
#                  number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: petclinic
spec:
  ingressClassName: nginx
  rules:
    - host: www.team3.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petclinic        # petclinic Service 이름
                port:
                  number: 80         # Service 포트

